### ISSUE TITLE
How to use it to render Jbig2 images in canvas or image

### ISSUE THREAD

**Issue by mzesheikh** [igstan/jbig2.js#1]
Hi,
great work . Can I use it to render jbig2 images in html canvas or image tag. Can you please provide a sample code

**Comment by igstan** [comment]
Unfortunately, I haven't gotten to finish this library, so it is still in an incomplete state. I'm also not sure when I'll resume work on it.

All I can do to help you is point to the [pdf.js](https://github.com/mozilla/pdf.js) library which includes a working jbig2 decoder. Last time I looked at it, the jbig2 decoder was partially implemented, in that it didn't support a certain type of (rare) encoding, but otherwise it's able to render jbig2 images.

Sorry I couldn't help more.
